adds confirm edit checkmark and slider handle, closes #1195
tijlleenders/ZinZen pull request #1206
Opened 2023-05-08 15:32 UTC by alpeshl

adds confirm edit checkmark and slider handle, closes #1195

2023-05-08 22:07 UTC, tijlleenders commented
Looking good @alpeshl !

I'm having trouble using the slider to close though.
@Tushar-4781 If that is tricky to implement we can merge this for now as the checkmark already has value - and make a different issue to implement slider?

2023-05-09 10:34 UTC, Tushar-4781 commented
> Looking good @alpeshl !
> 
> I'm having trouble using the slider to close though. @Tushar-4781 If that is tricky to implement we can merge this for now as the checkmark already has value - and make a different issue to implement slider?

@tijlleenders  The slider won't work because it just a line. I think @alpeshl misunderstood the context of slider. @alpeshl try using drag properties of html element to pull the slider for closing the pop up.

2023-05-09 12:37 UTC, alpeshl commented
> > Looking good @alpeshl !
> > I'm having trouble using the slider to close though. @Tushar-4781 If that is tricky to implement we can merge this for now as the checkmark already has value - and make a different issue to implement slider?
> 
> @tijlleenders The slider won't work because it just a line. I think @alpeshl misunderstood the context of slider. @alpeshl try using drag properties of html element to pull the slider for closing the pop up.

For now, I've added logic for slider handle to close the popup by implementing touch move gesture event. 

Since, we're using Modal component from `react-bootstrap`, it is not really easy to implement drag support and customize the existing behavior as expected.

Please check the update and let me know in case of any issue or feedback.

2023-05-09 13:34 UTC, Tushar-4781 commented
@alpeshl  Nicely done. Maybe by using margin or padding props, you can increase the tap area of the slider. Then it will work like charm.

However there is an issue to convert all modals into antd modals. So don't worry about that.

2023-05-10 05:03 UTC, alpeshl commented
> @alpeshl Nicely done. Maybe by using margin or padding props, you can increase the tap area of the slider. Then it will work like charm.
> 
> However there is an issue to convert all modals into antd modals. So don't worry about that.

done

2023-05-10 06:20 UTC, Tushar-4781 commented
@alpeshl please make the requested changes as well

2023-05-10 07:41 UTC, alpeshl commented
> @alpeshl please make the requested changes as well

I already pushed requested changes, could you please review and verify.

2023-05-16 10:14 UTC, alpeshl commented
@tijlleenders @Tushar-4781 can this be merged?

2023-05-16 10:22 UTC, Tushar-4781 requested changes

2023-05-17 05:24 UTC, alpeshl commented on src/components/GoalsComponents/GoalConfigModal/GoalConfigModal.tsx
> +            style={{ display: "flex",
Slider seems to be working fine. I've moved styles to scss module.

Let me know if you find any issue.

2023-05-20 14:11 UTC, Tushar-4781 approved these changes

2023-05-20 14:11 UTC, merged