feat: added language selection modal
tijlleenders/ZinZen pull request #1401
Opened 2023-08-10 06:31 UTC by FullStackSorcerer

Is this good enough?

2023-08-10 19:07 UTC, Tushar-4781 commented
i m not satisfied with the UI. @FullStackSorcerer will get back to you soon. thanks for your patience and time.

2023-08-10 19:25 UTC, tijlleenders commented
@FullStackSorcerer Yeah it's great work ... but I agree with Tushar a discussion is in place. 

I was a little surprised by the absence of borders. I thought something like a button was missing - some kind of UI glitch. I would definitely like a bit more border and a "Done" button or an obvious X in the corner. We don't really have UI/UX guidelines unfortunately...

I like how everything changes in realtime. React magic I guess. It will be more obvious you're making changea once we also translate the sub-menu buttons. Will make a separate issue for that.

2023-08-10 20:45 UTC, FullStackSorcerer commented
Do you think it would be better if I create a modal UI similar to the Add Goal modal, where I could put a heading "Change Language" and a "Close Icon" button in the same row, and in the body there were options for selecting languages?

2023-08-10 20:48 UTC, FullStackSorcerer commented
> i m not satisfied with the UI. @FullStackSorcerer will get back to you soon. thanks for your patience and time.

Thank you for the feedback. I appreciate you taking the time to share your thoughts on improving the UI. You're right, I still have some work to do. Please feel free to provide any additional suggestions - your input is valuable to me.

2023-08-11 04:36 UTC, tijlleenders commented
> @FullStackSorcerer @Tushar-4781 

> I was a little surprised by the absence of borders. 

To be fair, the layout is nearly identical to the onboarding screen - I've included a screenshot below so we can compare and make up our minds about what's missing.

_*We*_ still have some work to do - although I wonder if the absence of a full design should stop this PR. @FullStackSorcerer did a great job implementing the core functionality and we're didn't provide a design guideline. If there is a quick fix (like adding borders) then I suggest we do that and merge. If not - let's merge anyway.  

An imperfect UI that does the job is better than a perfect UI that doesn't exist yet.

![image](https://github.com/tijlleenders/ZinZen/assets/44887755/9ed5d4cc-6646-403d-ab83-5cb7eb45af13)

2023-08-11 07:09 UTC, FullStackSorcerer commented
> > @FullStackSorcerer @Tushar-4781
> 
> > I was a little surprised by the absence of borders.
> 
> To be fair, the layout is nearly identical to the onboarding screen - I've included a screenshot below so we can compare and make up our minds about what's missing.
> 
> __We__ still have some work to do - although I wonder if the absence of a full design should stop this PR. @FullStackSorcerer did a great job implementing the core functionality and we're didn't provide a design guideline. If there is a quick fix (like adding borders) then I suggest we do that and merge. If not - let's merge anyway.
> 
> An imperfect UI that does the job is better than a perfect UI that doesn't exist yet.
> 
> ![image](https://user-images.githubusercontent.com/44887755/259923746-9ed5d4cc-6646-403d-ab83-5cb7eb45af13.png)

I would make some quick fixes and then you could merge it.

2023-08-11 14:37 UTC, Tushar-4781 commented
@FullStackSorcerer nice spirit why don't you do one thing, we have a common folder right in our codebase. just make that language list UI a common component and then use it in modal and the language choice page. this would save lot of LOC(s) for use and the UI will be consistent and same.

2023-08-12 08:19 UTC, FullStackSorcerer commented
> @FullStackSorcerer nice spirit why don't you do one thing, we have a common folder right in our codebase. just make that language list UI a common component and then use it in modal and the language choice page. this would save lot of LOC(s) for use and the UI will be consistent and same.

I have reused the LanguageList component in order to make the UI consistent across both places it is used, and prevent duplicating a LOC(s).

2023-08-12 09:44 UTC, tijlleenders commented
LGTM  Nice work @FullStackSorcerer 
I didn't looj qt code just UI/UX.
The selection highlights and there is plenty of space to click outside on backdrop so don't think we need an extra button.

@Tushar-4781  agree?

2023-08-12 14:48 UTC, Tushar-4781 commented
> LGTM Nice work @FullStackSorcerer I didn't looj qt code just UI/UX. The selection highlights and there is plenty of space to click outside on backdrop so don't think we need an extra button.
> 
> @Tushar-4781 agree?

@tijlleenders i think we can close the popup once you choose the option ??

2023-08-12 14:48 UTC, Tushar-4781 requested changes
If i m in subgoals and i choose the select language option it shows my goals page in background

2023-08-12 16:19 UTC, tijlleenders commented
@Tushar-4781 
It's not clear to me what the requested changes are for the second comment.

For the first nice catch. I do return to the right subgoal after clickingbon the backdrop.

2023-08-12 16:29 UTC, Tushar-4781 commented
> @Tushar-4781 It's not clear to me what the requested changes are for the second comment.
> 
> For the first nice catch. I do return to the right subgoal after clickingbon the backdrop.

just open any popup i mentioned like share modal or add feelings modal. you will get it

2023-08-12 16:29 UTC, Tushar-4781 commented
![Uploading image.png…]()

2023-08-12 16:52 UTC, Tushar-4781 requested changes

2023-08-12 16:52 UTC, Tushar-4781 commented on src/components/LanguageChangeModal/index.scss
> +    padding: 0% !important;
please don't apply padding - 0 like this, it will be applied to all our popups make a class or id to apply it for this popup only

2023-08-12 16:52 UTC, Tushar-4781 commented on src/utils/index.ts
> +export const getLanguages = () => {
move it constants folder. not utils

2023-08-12 19:35 UTC, tijlleenders commented
> @tijlleenders i think we can close the popup once you choose the option ??

Yeah that's even better!

2023-08-16 10:38 UTC, tijlleenders commented
Thanks @FullStackSorcerer :)

LGTM @Tushar-4781 
Are requested changes resolved?

2023-08-16 10:52 UTC, FullStackSorcerer commented
I've relocated the languages data into the constants folder. Also, I've ensured that the modal now closes as soon as a language is picked, and I've successfully tackled the UI bug that was causing issues with the other modals.

2023-08-17 18:05 UTC, Tushar-4781 requested changes
I can't close language popup using browser back button

2023-08-17 18:05 UTC, Tushar-4781 commented on src/components/LanguageChangeModal/LanguageChangeModal.tsx
> +      onCancel={() => close(!open)}
we have to use window.history.back() to close the popup and update the browser history state

2023-08-19 13:29 UTC, tijlleenders commented
@Tushar-4781 Can you finish this to avoid it falling too far behind on the codebase?  

Feels like we were nearly there.

2023-08-19 14:12 UTC, FullStackSorcerer commented
I'll finish by today.

2023-08-19 15:07 UTC, tijlleenders commented
Wow @FullStackSorcerer getting this in this week would be great! It'll help us catch some translation todo's too :)

2023-08-19 15:38 UTC, FullStackSorcerer commented
Have a look, I think it's perfect now.

2023-08-22 16:05 UTC, Tushar-4781 requested changes

2023-08-22 16:05 UTC, Tushar-4781 commented on src/components/LanguageChoice/LanguagesList.tsx
> +    else close(!open)
@FullStackSorcerer  the core idea is to change the state of language in local storage and then use window.history.back() to close the popup. browser's state will not get updated if you will close via setState method. 
To reproduce the error ; select a language and go to journal page you will see the language popup will come again.

2023-08-23 16:33 UTC, Tushar-4781 approved these changes

2023-08-24 18:59 UTC, tijlleenders approved these changes
Woooh000!!! 🎉🥳
You brought this one home @FullStackSorcerer 

Thanks ;)

2023-08-24 18:59 UTC, merged

2023-08-24 19:00 UTC, tijlleenders commented
Will push to prod in a few days.