improve goal adding ux
tijlleenders/ZinZen pull request #1628
Opened 2023-11-26 09:02 UTC by vinaybadgujar102

resolves #1618

2023-11-26 09:40 UTC, tijlleenders commented
@vinaybadgujar102 
The + button is not visible on DuckDuckGo (mobile). I don't think we should waste too much time on tweaking minor UI details for different browsers - but the basic elements should be visible...

Also, can you use a consistent font size (like the ones used for Goal text)?  
Having different font sizes mixed on screen makes it noisy and harder to read.

It would be nice if there is no gap between the 'Goal button' and the '+' button. That will also avoid the + button from 'jumping' to a different place after initial tap.

2023-11-27 11:38 UTC, vinaybadgujar102 commented
@tijlleenders I have made changes as mentioned

2023-11-29 17:25 UTC, tijlleenders commented
Yeah nice @Tushar-4781 OK to merge?

2023-11-29 18:50 UTC, Tushar-4781 requested changes

2023-11-29 18:50 UTC, Tushar-4781 commented on src/components/BottomNavbar/BottomNavbar.tsx
> +        {isAddBtnVisible && <GlobalAddBtn add={title} />}
hi @vinaybadgujar102  please put this back inside the journal button. It was done intentionally. as we have to keep the Add button right above to the journal icon. if you move this button out we will loose the alignment on mobile screens. for example this device
![image](https://github.com/tijlleenders/ZinZen/assets/39093015/47ed6520-9e8f-4949-a7a3-912f14d33c40)

2023-12-02 06:58 UTC, vinaybadgujar102 commented
resolves #1644

2023-12-02 10:48 UTC, Tushar-4781 approved these changes

2023-12-02 10:52 UTC, merged