make mytime less busy
tijlleenders/ZinZen pull request #1671
Opened 2023-12-06 14:36 UTC by vinaybadgujar102

resolves #1624 
also separated UI elements such as GoalTiming and TaskOption from MyTimeline into individual components for improved maintainability and readability.

2023-12-09 11:38 UTC, Tushar-4781 reviewed
@tijlleenders please confirm the UI

2023-12-09 11:38 UTC, Tushar-4781 commented on src/components/MyTimeComponents/MyTimelineElements.tsx
@vinaybadgujar102 please split these components in separate files. file cannot have more than 1 main component

2023-12-09 15:57 UTC, Tushar-4781 requested changes
Please do the following changes & resolve merge conflicts and we are good to go

2023-12-09 15:57 UTC, Tushar-4781 commented on src/components/MyTimeComponents/MyTimeline/GoalTiming.tsx
> +  const renderTime = (time: string | null) =>
make it simple. accept time only. don't call the function if your value is null

2023-12-09 15:57 UTC, Tushar-4781 commented on src/components/MyTimeComponents/MyTimeline/GoalTiming.tsx
> +      {renderTime(startTime)}
do conditional rendering here

2023-12-10 14:06 UTC, tijlleenders commented
@vinaybadgujar102 Please take PR out of draft mode and ask Tushar to review when you're done.

2023-12-10 15:04 UTC, Tushar-4781 approved these changes

2023-12-10 15:04 UTC, merged