refactor: input budget field to include min/max per day and week
tijlleenders/ZinZen pull request #1673
Opened 2023-12-08 06:01 UTC by vinaybadgujar102

resolves #1595

2023-12-08 07:44 UTC, tijlleenders requested changes
I don't see any goals/budgets being sent to the scheduler...
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/d8f44944-b9f2-48c9-a6a6-905651e99cff)

2023-12-09 03:37 UTC, vinaybadgujar102 commented
as mentioned in #1594, not all entities are currently being sent to the scheduler. 
You can create new goals with duration and check the budget structure.

2023-12-09 03:54 UTC, tijlleenders commented
@vinaybadgujar102 
I understand something without a duration isn't being sent. Budgets are an exception to this rule. Maybe that was an oversight.

The default goals are budgets - so I shouldn't have to create anything for them to be sent to the scheduler.

2023-12-09 03:59 UTC, tijlleenders commented
Added #1674 to require budgets being sent.

2023-12-13 16:49 UTC, tijlleenders commented
Looks good I think.
@vinaybadgujar102 We're now just sending everything, right?

@Tushar-4781 Agree on code?

2023-12-14 03:01 UTC, vinaybadgujar102 commented
Yeah, we are sending everything to the scheduler

2023-12-16 09:29 UTC, Tushar-4781 requested changes

2023-12-16 09:29 UTC, Tushar-4781 commented on src/Interfaces/IScheduler.ts
> +    maxPerDay: number | undefined;
do like this 
minPerDay?: number

2023-12-16 17:49 UTC, Tushar-4781 approved these changes

2023-12-16 17:50 UTC, Tushar-4781 commented
@vinaybadgujar102 please resolve the conflicts so that we can merge :)

2023-12-17 04:37 UTC, tijlleenders approved these changes

2023-12-17 04:37 UTC, merged