focus action not working for today
tijlleenders/ZinZen pull request #1687
Opened 2023-12-11 09:23 UTC by vinaybadgujar102

2023-12-11 11:53 UTC, tijlleenders commented
Yup, it's working again.

2023-12-11 14:06 UTC, Tushar-4781 requested changes

2023-12-11 14:06 UTC, Tushar-4781 commented on src/components/MyTimeComponents/MyTimeline/MyTimeline.tsx
> +      handleFocusClick(task);
return this function directly

2023-12-13 13:38 UTC, Tushar-4781 approved these changes

2023-12-13 13:39 UTC, merged