better color selector with popup
tijlleenders/ZinZen pull request #1689
Opened 2023-12-13 13:50 UTC by vinaybadgujar102

resolves #1483 

- Moved colorpicker to top of config modal
- Revamped colorpicker component. Added a compact, scrollable color palette popup to ColorPicker for improved user interface

2023-12-13 16:45 UTC, tijlleenders commented
Looks good!
I'm sure we'll want some minor design changes - but this is a lot nicer in my opinion.

2023-12-13 16:45 UTC, tijlleenders submitted a review, later dismissed

2023-12-16 17:48 UTC, Tushar-4781 requested changes
@vinaybadgujar102 please make this 2 minor changes and we are gtg

2023-12-16 17:48 UTC, Tushar-4781 commented on src/components/GoalsComponents/GoalConfigModal/ConfigGoal.tsx
> +import ColorPalette from "@src/common/ColorPicker";
the component name must match with file name. can you please fix this :)

2023-12-16 17:48 UTC, Tushar-4781 commented on src/global.scss
> +.color-picker-container {
global is getting crowder. can you create an index.scss file for this color picker component ?

2023-12-23 08:53 UTC, Tushar-4781 submitted a review, later dismissed
@vinaybadgujar102 please resolve the conflicts and after that we can merge

2023-12-23 15:56 UTC, Tushar-4781 approved these changes

2023-12-23 15:56 UTC, merged