show feeling history as a timeline in feelings page
tijlleenders/ZinZen pull request #1716
Opened 2023-12-24 11:41 UTC by vinaybadgujar102

resolves #1692

2023-12-25 07:41 UTC, tijlleenders requested changes
This is good - just reverse the order:
![1225_084016_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/74c8da3e-6ec2-4f06-8586-1bb91712197c)

2023-12-25 12:40 UTC, vinaybadgujar102 commented
@tijlleenders check if the order is correct now.

2023-12-26 05:34 UTC, tijlleenders submitted a review, later dismissed
The ordering is good now ... but somehow the Add button doesn't work after letting one day pass.

2023-12-26 06:04 UTC, vinaybadgujar102 commented
it seems to work correctly on my setup. do add button stops working for just the feelings page or overall app. can you post screen recording?

2023-12-26 08:02 UTC, tijlleenders commented
The screen recording is not interesting - since there is nothing visibly going wrong. 
The Add button works correctly on the MyGoals page. It's only on MyFeelings that it doesn't work. If you can't reproduce then let's see after we merge.

2023-12-29 20:57 UTC, tijlleenders commented
It works in Chrome.

2023-12-29 21:00 UTC, tijlleenders approved these changes

2023-12-29 21:00 UTC, tijlleenders commented
@Tushar-4781 OK to merge?

2023-12-31 04:18 UTC, Tushar-4781 requested changes

2023-12-31 04:18 UTC, Tushar-4781 commented on src/pages/ShowFeelingsPage/useFeelingsData.ts
> +const useFeelingsData = (trigger: boolean) => {
Nice work @vinaybadgujar102 move this hook to the hooks folder

2023-12-31 11:20 UTC, tijlleenders approved these changes

2023-12-31 11:21 UTC, merged