Fixed Issue #1774
tijlleenders/ZinZen pull request #1780
Opened 2024-01-19 16:30 UTC by harith-hacky03

Switch edit layout rows for easier access #1774 is fixed Successfully

2024-01-19 16:41 UTC, tijlleenders requested changes
Thanks for the effort @harith-hacky03 but I don't see any layout change...

This is purely shifting things around in the layout so it should just be a switcharound.

I didn't expect any new imports either. Why do you need that?

2024-01-19 16:45 UTC, harith-hacky03 commented
@tijlleenders Now the keyboard is not hiding the create goal button since I moved the layout to the top in the mobile device. Is it okay ?

2024-01-19 16:46 UTC, harith-hacky03 commented
![Screenshot_2024-01-19-22-16-14-35_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/tijlleenders/ZinZen/assets/108193091/190d3216-c462-48dc-a637-dc911c2c9e52)

2024-01-19 17:34 UTC, tijlleenders commented
@harith-hacky03 Yes, that's OK I guess. This was not documented as an alternative fix. The downside of this is that we lose the context of the parent goal.  

I guess we can evaluate your option for a while.

**Could you also switch the rows too?**  

We'll then merge it and use it for a while.
We can always revert one and/or the other if it reduces the overall experience.

2024-01-19 17:36 UTC, harith-hacky03 commented
@tijlleenders Sure ! I am ready to do it. Can you please provide some details with image with rows wants to be changed . Thank you

2024-01-19 17:40 UTC, tijlleenders commented
Sure @harith-hacky03 I guess the image in the issue is not clear enough.  

Here's the desired state:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/98144e4d-6a9e-47d4-a0c9-5890d07cbd65)

2024-01-19 20:28 UTC, harith-hacky03 commented
@tijlleenders Yeah! Thank you

2024-01-20 14:16 UTC, harith-hacky03 commented
@tijlleenders  Yeah i changed the rows . Hope it helps. If any changes is needed ping me.

2024-01-20 15:35 UTC, tijlleenders approved these changes
Excellent @harith-hacky03 !

@Tushar-4781 OK on code too?

2024-01-20 15:37 UTC, harith-hacky03 commented
@tijlleenders Is it good now ?

2024-01-20 15:45 UTC, tijlleenders commented
@harith-hacky03 Yeah it's great.  

Just asking @Tushar-4781 to validate the code before we merge. I mostly look at the UI/UX/feature side of things.

2024-01-20 15:46 UTC, harith-hacky03 commented
@tijlleenders  Thank you.

2024-01-20 18:16 UTC, Tushar-4781 requested changes
hi Harith, thanks for your contributions. can you please check the following comments and then we will be gtg

2024-01-20 18:16 UTC, Tushar-4781 commented on package.json
> +    "cypress": "^13.6.3",
please discard this as its not in the scope of this PR

2024-01-20 18:16 UTC, Tushar-4781 commented on src/common/ZModal.tsx
> +  const isMobileDevice = () => {
umm, i don't see any change . any specific reason to add this check ? why no just keep it centered by default ?

2024-01-20 18:16 UTC, Tushar-4781 commented on src/common/ZModal.tsx
> +import { read } from "fs";
can you remove this please.

2024-01-20 18:16 UTC, Tushar-4781 commented on package-lock.json
please discard this as well

2024-01-20 18:32 UTC, harith-hacky03 commented on package-lock.json
Is it okay now?

2024-01-20 18:49 UTC, tijlleenders commented
@harith-hacky03 

CI is failing with message `npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.`

2024-01-20 19:23 UTC, harith-hacky03 commented
@tijlleenders Is it okay now?

2024-01-20 19:43 UTC, tijlleenders commented
@harith-hacky03 Yup, all good:
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/2f913f3c-63fd-411f-bbd5-ad3ecb8136f3)

@Tushar-4781 will merge if all code issues are confirmed resolved.

Thanks.

2024-01-21 14:37 UTC, Tushar-4781 commented on package-lock.json
@harith-hacky03 please discard the package and lock files from this PR and then we are gtg

2024-01-21 14:46 UTC, harith-hacky03 commented on package-lock.json
I wanna remove the types/crypto file from the package.json?

2024-01-21 14:47 UTC, harith-hacky03 commented on package-lock.json
@Tushar-4781 Or wanna remove the package.json file . please provide some details in brief

2024-01-24 18:04 UTC, tijlleenders commented
@harith-hacky03 The only thing blocking this PR is the modified package files.  
If you look at the '[files changed by this pr](https://raw.githubusercontent.com/tijlleenders/ZinZen/main/package-lock.json)' - you can see the package files are not the same.  

Since you're merging from a fork I can't fix this for you.  
Just replace the contents of the `package.json` and `package-lock.json` with the code from main branch - and there will be no diffs: 
- https://github.com/tijlleenders/ZinZen/blob/main/package-lock.json
- https://raw.githubusercontent.com/tijlleenders/ZinZen/main/package.json

2024-01-24 18:10 UTC, harith-hacky03 commented
@tijlleenders  Is it okay now?!

2024-01-24 18:10 UTC, tijlleenders approved these changes
Great!

Thanks a bunch @harith-hacky03 ;)

2024-01-24 18:15 UTC, harith-hacky03 commented
@tijlleenders  Thank you for the good guidance. Can you merge it now without any difficulties?!

2024-01-24 18:15 UTC, merged