allow users to set 0 as minimum budget value
tijlleenders/ZinZen pull request #1802
Opened 2024-01-24 10:43 UTC by vinaybadgujar102

resolves #1788

2024-01-24 11:02 UTC, tijlleenders requested changes
Looks good @vinaybadgujar102 

There is one small glitch. When you drag from 1 to 0 and don't stop dragging till you're way outside the window - the modal closes unexpectedly.

2024-01-24 12:03 UTC, vinaybadgujar102 commented
@tijlleenders This issue already existed in the codebase and is not directly related to the changes made here.  I suggest we handle this as a separate issue.

2024-01-24 12:35 UTC, tijlleenders commented
@vinaybadgujar102 Sure, please add the issue.

2024-01-26 08:08 UTC, Tushar-4781 approved these changes

2024-01-26 08:08 UTC, merged