edit: set dark theme as default for new users
tijlleenders/ZinZen pull request #1826
Opened 2024-02-05 14:48 UTC by vinaybadgujar102

resolves #1820 

- modified getDarkModeValue() to return "on" by default
- modified useApp() hook to set "darkMode" key in localStorage to "on"

2024-02-05 16:10 UTC, tijlleenders requested changes
Can't read the question on the language choice page.

2024-02-05 16:11 UTC, tijlleenders commented
This is not dark mode compatible: 
![image](https://github.com/tijlleenders/ZinZen/assets/44887755/4dc34df3-2015-4248-8085-0e83a9597380)

2024-02-06 05:45 UTC, tijlleenders approved these changes
Yeah, this works.

@Tushar-4781 Code OK?

2024-02-06 15:01 UTC, Tushar-4781 approved these changes

2024-02-06 15:01 UTC, merged