restrict min-max weekly hours based on daily budget hours
tijlleenders/ZinZen pull request #1847
Opened 2024-03-17 04:26 UTC by vinaybadgujar102

resolves #1783

2024-03-17 05:55 UTC, tijlleenders requested changes
Pretty awesome @vinaybadgujar102 

I did however (not clear how to reproduce) get into an invalid state:  
![50_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/2d2d3952-1882-4fe6-8eea-e09df6dc6c45)

Another thing is that the number of days is always assumed to be seven. Not sure if that can be taken into account in this issue or if we shoukd make a separate issue for that.

2024-03-25 13:56 UTC, vinaybadgujar102 commented
@tijlleenders, please check now to see if the mentioned concern has been resolved

2024-03-28 07:56 UTC, vinaybadgujar102 commented
@tijlleenders made the requested changes, please review

2024-03-29 04:35 UTC, tijlleenders requested changes
The budget is still unresponsive to changes in days of the week:
![2024-03-29 budget unresponsive to days of the week](https://github.com/tijlleenders/ZinZen/assets/44887755/35d60ded-50e7-4538-85a3-b96ccc35e9b7)

2024-03-29 11:53 UTC, tijlleenders requested changes
Perfect!

Only... after saving / close / open thr preview is not visible anymore:

![5232_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/4d343327-331d-4b25-844d-225b6c85b891)

2024-03-29 12:10 UTC, vinaybadgujar102 commented
@tijlleenders, fixed

2024-03-29 16:02 UTC, tijlleenders submitted a review, later dismissed
Super!

@Tushar-4781 Code OK?

2024-03-29 17:34 UTC, Tushar-4781 requested changes

2024-03-29 17:34 UTC, Tushar-4781 commented on src/components/GoalsComponents/GoalConfigModal/ConfigGoal/BudgetAccordian/BudgetDaySlider.tsx
i don't think its necessary to create every single element as seperate component unless it is used by multiple components.  not a good move for this 16 LOC. plz merge these components of config goal

2024-03-30 03:37 UTC, vinaybadgujar102 commented on src/components/GoalsComponents/GoalConfigModal/ConfigGoal/BudgetAccordian/BudgetDaySlider.tsx
So should I merge all the separated components or only the mentioned one "DailyBudgetSlider"?

2024-03-30 08:39 UTC, Tushar-4781 commented on src/components/GoalsComponents/GoalConfigModal/ConfigGoal/BudgetAccordian/BudgetDaySlider.tsx
merge all of them

2024-03-30 10:06 UTC, tijlleenders approved these changes

2024-03-30 10:07 UTC, vinaybadgujar102 commented on src/components/GoalsComponents/GoalConfigModal/ConfigGoal/BudgetAccordian/BudgetDaySlider.tsx
Done

2024-03-30 10:09 UTC, tijlleenders requested changes
Found a last minute glitch:

![0_110815_DuckDuckGo.jpg](https://github.com/tijlleenders/ZinZen/assets/44887755/fbfd96e7-5fd5-4181-abca-4c337723b7b5)

2024-03-30 10:16 UTC, tijlleenders commented
Seems this only happens when you don't expand the budget menu - and then try to add / remove days. Adding also doesn't go above the initial amount, even though all days may be selected.

2024-03-30 10:36 UTC, vinaybadgujar102 commented
The week budget hour value is correctly applied in mentioned screenshot. It is between the constraints as per the condition:
Min: 24 Max: 40. 

If the applied weekly budget values fails to satisfy both min-max constraints then it resolves to single value (x hrs) accordingly, thats why no range (x hrs - x hrs) is displayed in summary.

Same happens with daily budget hours when between slider is changed.

2024-03-30 12:10 UTC, tijlleenders approved these changes
@vinaybadgujar102 You're right - somehow as a user I expect things to change when I remove a whole day... but let's try this out for a whioe and see how this goes in real life.

2024-04-09 06:33 UTC, merged