contacts links in goal title (WIP)
tijlleenders/ZinZen pull request #1905
Opened 2024-05-01 06:35 UTC by vinaybadgujar102

resolves #1895

2024-05-01 15:47 UTC, tijlleenders approved these changes
@vinaybadgujar102 Awesome!

One step closer to getting my contacts away from my phone/SIM/BigTech lock-in!

Also nice that I can organize them hierarchically - and store talking points alongside the contact :).

2024-05-02 11:08 UTC, Tushar-4781 requested changes

2024-05-04 14:43 UTC, vinaybadgujar102 commented on src/components/GoalsComponents/MyGoal/GoalTitleProcessors.tsx
The mentioned file contains components that simply render the processed goal titles passed to them while applying some cosmetic changes. The actual processing of the goal titles is carried out by the functions present in "patterns.ts". For better clarity, I have renamed the file to GoalTitleHandler.ts. 
I think we can't make a custom hook out of it.

2024-05-08 06:53 UTC, Tushar-4781 requested changes

2024-05-08 06:53 UTC, Tushar-4781 commented on src/components/GoalsComponents/MyGoal/GoalTitleProcessors.tsx
my bad, lemme elaborate a bit 

1. useClickHandler: create a custom hook that generates event handlers (handleClick and handleKeyPress) and an ariaLabel based on the provided action and aria label prefix.

2. useHandler: create a another custom hook that gives JSX components for URL and Tel handlers. It takes an action function (such as opening a URL or calling a phone number) and an aria label prefix. Inside this hook, it will utilize the useClickHandler to manage click events and aria label generation.

3. Exported Hooks:  now export ur handle hooks
useUrlHandler: Returns a hook instance specifically for URL handling. It uses useHandler with appropriate actions (window.open) and aria label prefix ("Open").
useTelHandler: Returns a hook instance specifically for Tel handling. It also uses useHandler but with different actions (window.location.href) and aria label prefix ("Call").

i hope this explanation helps

2024-05-11 07:46 UTC, vinaybadgujar102 commented on src/components/GoalsComponents/MyGoal/GoalTitleProcessors.tsx
@Tushar-4781 I tried but couldn't come up with the code. If possible please add the commits to this PR with required changes

2024-05-25 14:07 UTC, tijlleenders commented
@Tushar-4781 Can you help get this one in?

2024-05-28 09:08 UTC, Tushar-4781 approved these changes

2024-05-28 09:13 UTC, merged