navigate to subgoal with one click and moved goalItem summary
tijlleenders/ZinZen pull request #1929
Opened 2024-06-01 08:47 UTC by vinaybadgujar102

resolves #1924

2024-06-01 08:57 UTC, tijlleenders requested changes
Excellent!

Can you replace the pipe | with a comma ,?

Also please update the tests (or migrate and update them to Playwright if not much effort).

2024-06-01 09:21 UTC, vinaybadgujar102 commented
> Also please update the tests (or migrate and update them to Playwright if not much effort).

@tijlleenders, I think for smaller UI checks and functionalities, we can use a unit testing library. Playwright is an E2E testing library, and E2E tests are expensive to run and hard to maintain. So, for complex UI interactions (like the collaboration feature), we can use Playwright. For smaller UI and feature testing, we can rely on unit testing libraries like Jest or Vitest.

2024-06-01 09:30 UTC, tijlleenders commented
Different tests for different purposes, I agree. 

Since the app is still very much in flux - any test is extra work that might get invalidated soon. So I only want to do end-to-end testing on major features.

For now I don't think investing in unit tests is worth it, unless you do it as part of your TDD flow.  

So for any test currently failing please explain what it is testing - so we can decide on a case-by-case basis what the appropriate level of the test is - and if we want it at this point in the project.

2024-06-01 10:03 UTC, tijlleenders commented
@Tushar-4781 @vinaybadgujar102 Do you agree to invest in lower level test sparingly - as the expected rate of change is higher on the internals?

2024-06-01 11:24 UTC, vinaybadgujar102 commented
> So for any test currently failing please explain what it is testing - so we can decide on a case-by-case basis what the appropriate level of the test is - and if we want it at this point in the project.

We currently have 6 failing Cypress tests:

- **Goals Page Title:** Verifies that the page title is displayed correctly on the Goals Page.
- **Search Input Visibility:** Checks if the search input is shown when the search icon is clicked.
- **Settings Dropdown Open:** Ensures the settings dropdown opens when the settings icon is clicked.
- **Close Settings Dropdown:** Verifies that the settings dropdown closes when clicking outside of it.
- **Dark Mode Toggle:** Tests the functionality of toggling dark mode when the Switch Mode button is clicked.
- **Conditional Settings Display:** Ensures the Zinzen settings are only displayed on the MyJournal or My Time pages.

2024-06-01 11:39 UTC, tijlleenders commented
@vinaybadgujar102 These are all high-level UI checks - for which I think it is appropriate to use a UI testing framework like Cypress/Playwright - don't you?  I have a hard time imagining how you would even do a UI check using a unit testing framework. For me unit testing is a relatively simple test on a specific function or module.  
No idea what the last test is for though. What is this 'settings display'?

2024-06-03 12:53 UTC, vinaybadgujar102 commented
@tijlleenders, I'm relatively new to testing, but I've learned that basic UI checks can be handled using a unit testing library like Jest. I think @Tushar-4781 might have some valuable insights to add on

>  No idea what the last test is for though. What is this 'settings display'?

The last test ensures that search button is only visible on Goals page and not others.

2024-06-06 05:23 UTC, tijlleenders submitted a review, later dismissed
Awesome @vinaybadgujar102 !

@Tushar-4781 Code OK?

2024-06-09 04:11 UTC, Tushar-4781 requested changes

2024-06-09 04:11 UTC, Tushar-4781 commented on src/hooks/useGoalSummary.ts
can we just use "?" that would save some LOC(s)

2024-06-09 04:20 UTC, vinaybadgujar102 commented on src/hooks/useGoalSummary.ts
Are you suggesting replacing the if statements?

2024-06-09 04:21 UTC, Tushar-4781 commented on src/hooks/useGoalSummary.ts
yup

2024-06-09 07:47 UTC, Tushar-4781 approved these changes

2024-06-09 07:47 UTC, merged