port cypress test to playwright and remove cypress
tijlleenders/ZinZen pull request #1942
Opened 2024-06-29 13:59 UTC by vinaybadgujar102

resolves #1879

2024-06-29 14:12 UTC, tijlleenders requested changes
Nice!
Did you do a search for all occurences of 'cypress' to remove everything?

I think it is mentioned in the Readme.md

2024-06-30 06:32 UTC, vinaybadgujar102 commented
@tijlleenders, I previously searched for and removed all occurrences of Cypress, but it seems one instance in the README was missed. I have now updated it in the latest commit.

2024-06-30 06:34 UTC, tijlleenders approved these changes
Great!

@Tushar-4781 code OK?

2024-07-07 06:25 UTC, Tushar-4781 approved these changes

2024-07-07 06:25 UTC, merged