feat: implement automatic trash cleanup
tijlleenders/ZinZen pull request #1948
Opened 2024-07-10 05:42 UTC by vinaybadgujar102

2024-07-10 05:48 UTC, tijlleenders submitted a review, later dismissed
Cool, I will check this in dev after we merge.

@Tushar-4781 Code OK?

2024-07-12 15:13 UTC, Tushar-4781 requested changes

2024-07-12 15:13 UTC, Tushar-4781 commented on src/api/TrashAPI/index.ts
> +  console.log(`Deleted ${oldTrashItems.length} items from trash older than ${TRASH_RETENTION_DAYS} days.`);
we can remove this log

2024-07-12 15:13 UTC, Tushar-4781 commented on src/api/TrashAPI/index.ts
> +
no need to leave line breaks

2024-07-12 15:13 UTC, Tushar-4781 commented on src/hooks/useApp.tsx
> +    initializeTrashManagement();
u can directly call checkAndCleanupTrash

2024-07-14 05:57 UTC, vinaybadgujar102 commented
@Tushar-4781 made the requested changes in the latest commit

2024-07-18 05:07 UTC, Tushar-4781 approved these changes

2024-07-18 05:07 UTC, merged