code-snippets
tijlleenders/ZinZen pull request #1978
Opened 2024-07-26 07:10 UTC by Nicholas-Kipkoech

@Nicholas-Kipkoech Please add which issue your PRs resolve so they are closed automatically. This will only happen when merging to main but even for merging to develop branch it is good practice so reviewer can check what the PR resolves.

Resolves #1965

2024-07-26 09:12 UTC, tijlleenders requested changes
Please add which issue this PR resolves. The title is technical.

2024-07-26 09:56 UTC, tijlleenders requested changes
Great!

When adding something with only at the front, the ticks don't show.
"```Ticks don't show"

Minor detail, but still. Actually, now that I think of it, can we make it so that adding ticks in the beginning only is sufficient? That way if you type in something you don't need the extra closing ticks.

2024-07-26 10:00 UTC, Nicholas-Kipkoech commented
@tijlleenders Noted.

2024-07-26 10:18 UTC, tijlleenders requested changes
When changing a code snippet back into a Goal, I can´t click on it to go 'into the Goal'.  

Given this, now I realize: Please check or add functionality to disallow changing a Goal into a Code snippet if there are subGoals.

2024-07-26 10:19 UTC, tijlleenders commented
[Screencast from 2024-07-26 12-16-39.webm](https://github.com/user-attachments/assets/6c7f9e24-8a0a-4d0c-9c92-01a5452b9111)

2024-07-26 10:20 UTC, tijlleenders commented
Actually, none of the Goals can be 'entered'... 
Wasn't this fixed in develop? Maybe you need to pull in the latest changes.

2024-07-26 11:48 UTC, Nicholas-Kipkoech commented
> When changing a code snippet back into a Goal, I can´t click on it to go 'into the Goal'.
> 
> Given this, now I realize: Please check or add functionality to disallow changing a Goal into a Code snippet if there are subGoals.

Alright, noted

2024-07-27 06:13 UTC, Nicholas-Kipkoech commented
@tijlleenders I have added the logic to disallow users from changing the goal to code it has a sublist. Toast message is also shown when you try to update the goal to code.

2024-07-27 06:28 UTC, tijlleenders approved these changes
Nicely done @Nicholas-Kipkoech 

I will make a low prio issue to adapt the icon to the ZinZen icon style, but that is low prio as it is not worth the time right now.

@Tushar-4781 Is the code OK too?

2024-07-28 15:54 UTC, Tushar-4781 requested changes

2024-07-28 15:54 UTC, Tushar-4781 commented on src/assets/CopyIcon.tsx
> +        {" "}
do we need this spaces ?

2024-07-28 15:54 UTC, Tushar-4781 commented on src/components/GoalsComponents/MyGoal/MyGoal.tsx
> +  const isCode = isGoalCode(title);
You don't need to define it here since it's only used in one place. Put it directly in the if condition instead.

2024-07-29 15:36 UTC, tijlleenders commented
@Nicholas-Kipkoech Please re-request a review from Tushar when you're done.

2024-07-30 10:44 UTC, Tushar-4781 requested changes

2024-07-30 10:44 UTC, Tushar-4781 commented on src/components/GoalsComponents/MyGoal/MyGoal.tsx
> +  const { title } = goal;
no need to deconstruct it at higher level. use it directly.

2024-08-16 06:23 UTC, tijlleenders commented
@Tushar-4781 Can you get this in?

2024-08-28 11:21 UTC, vinaybadgujar102 commented
@Tushar-4781 , I have merged latest commits. You can review it.

2024-08-31 05:15 UTC, Tushar-4781 approved these changes

2024-08-31 05:15 UTC, merged