adjust not on blocks for scheduler input
tijlleenders/ZinZen pull request #1996
Opened 2024-07-27 14:04 UTC by vinaybadgujar102

resolves #1959

2024-07-27 14:22 UTC, tijlleenders approved these changes
Awesome, this seems to fix my issues. Will have to use it for a while to see if it actually does the right things.

2024-07-27 14:23 UTC, tijlleenders commented
@Tushar-4781 Code ok?

2024-07-28 15:49 UTC, Tushar-4781 requested changes

2024-07-28 15:49 UTC, Tushar-4781 commented on src/api/TasksAPI/index.ts
> +    await db.transaction("rw", db.taskCollection, async () => {
remove the transaction its not required

2024-07-28 15:49 UTC, Tushar-4781 commented on src/api/TasksAPI/index.ts
> +      .filter((block) => {
try this    .filter((block) => new Date(block.end) > today)

2024-08-03 04:34 UTC, vinaybadgujar102 commented
@Tushar-4781, you can review this

2024-08-03 06:17 UTC, Tushar-4781 approved these changes

2024-08-03 06:17 UTC, merged