introduce "Not now" task option and move skip to not now modal
tijlleenders/ZinZen pull request #2013
Opened 2024-08-04 10:10 UTC by vinaybadgujar102

2024-08-04 11:37 UTC, tijlleenders approved these changes
Looks good.

2024-08-16 05:46 UTC, vinaybadgujar102 commented
@Tushar-4781 ready for review

2024-08-16 16:53 UTC, Tushar-4781 requested changes

2024-08-16 16:53 UTC, Tushar-4781 commented on src/components/MyTimeComponents/NotNow/NotNowModal.tsx
> +export default NowNowModal;
what's this ?

2024-08-18 14:15 UTC, Tushar-4781 approved these changes

2024-08-18 14:37 UTC, merged

2024-08-18 14:42 UTC, tijlleenders approved these changes
I'm not sure about the wording in the 'Not now' modal. I'm inclined to use 'postpone' but if you 'postpone' for 1h it could also be scheduled even earlier in the day - as you on have indicated the current slot ia not convenient...

Anyway. This is mergeable. We'll use this for a while and see.