subgoalhistory bug
tijlleenders/ZinZen pull request #2015
Opened 2024-08-05 07:22 UTC by vinaybadgujar102

2024-08-05 16:27 UTC, tijlleenders requested changes
It is hard to see what this fixes as the behavior in the PR is not correct. When I switch to MyTime from a subgoal and return, I expect to still be in the subGoal. Instead I'm returned to root level.

2024-08-06 07:30 UTC, vinaybadgujar102 commented
> When I switch to MyTime from a subgoal and return, I expect to still be in the subGoal. Instead I'm returned to root level.

@tijlleenders. This behaviour was introduced in develop branch and I thought this was what was expected. I should have checked the main branch.

You can review now.

2024-08-06 10:31 UTC, tijlleenders approved these changes

2024-08-08 19:34 UTC, Tushar-4781 approved these changes

2024-08-08 19:34 UTC, merged