navigate goals with arrow keys
tijlleenders/ZinZen pull request #2022
Opened 2024-08-14 08:24 UTC by vinaybadgujar102

resolves #1985

2024-08-16 05:22 UTC, tijlleenders requested changes
Excellent!  
The one thing missing is that when you navigate back up, the selector should also be visible, so that you can go left, then right immediately to return to where you were, instead of having to press down first.

2024-08-18 15:03 UTC, vinaybadgujar102 commented
> Excellent!
> The one thing missing is that when you navigate back up, the selector should also be visible, so that you can go left, then right immediately to return to where you were, instead of having to press down first.

@tijleenders, I implemented the requested change. However, I encountered an issue that I couldn't resolve. When a user navigates to another page, such as the Journal Page, and then returns to the Goals Page, the previously focused goal remains focused. The expected behavior should be that the focus resets. I'm not sure if this is the ideal approach, but it's what I believe should happen.

2024-08-18 15:22 UTC, tijlleenders requested changes
When I navigate to 'Walk' and press down, I get this error: "Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

2024-08-18 15:22 UTC, tijlleenders commented
> > Excellent!
> > The one thing missing is that when you navigate back up, the selector should also be visible, so that you can go left, then right immediately to return to where you were, instead of having to press down first.
> 
> @tijlleenders , I implemented the requested change. However, I encountered an issue that I couldn't resolve. When a user navigates to another page, such as the Journal Page, and then returns to the Goals Page, the previously focused goal remains focused. The expected behavior should be that the focus resets. I'm not sure if this is the ideal approach, but it's what I believe should happen.

I think it's fine to keep the focus.

2024-08-22 05:27 UTC, tijlleenders requested changes
This looks good now.

One tiny mod: When adding a new goal I´d like the focus to be on the newly created goal, instead of sticking to the nth in the list.

2024-08-23 16:46 UTC, vinaybadgujar102 commented
> One tiny mod: When adding a new goal I´d like the focus to be on the newly created goal, instead of sticking to the nth in the list.

We can address this in a new issue, as this PR is already somewhat complex.

2024-08-23 17:02 UTC, tijlleenders commented
No I think it should be fixed here, as the highlighted goal switch (it jumps to the previous goal) after adding a goal is unexpected and confusing, thus a bug.

2024-08-27 15:40 UTC, tijlleenders requested changes
Excellent.  

The one thing I'd like to add to this PR is that the line doesn't move the goal circle and title to the right a bit. It's a small thing, but annoying (or at least not adding any value) when things jump a few pixels when moving around the highlighter.

2024-08-28 10:24 UTC, tijlleenders requested changes
A lot better, but there is still a small budge in the Circle/Title:  
[Screencast from 2024-08-28 12-22-23.webm](https://github.com/user-attachments/assets/73a1aeb9-3518-4f1c-acc8-54330bed5d00)

Don't spend too much time, but see if you can eliminate it completely please.

2024-08-28 10:37 UTC, vinaybadgujar102 commented
> A lot better, but there is still a small budge in the Circle/Title:  
> 
> [Screencast from 2024-08-28 12-22-23.webm](https://github.com/user-attachments/assets/73a1aeb9-3518-4f1c-acc8-54330bed5d00)
> 
> 
> 
> Don't spend too much time, but see if you can eliminate it completely please.

I tried with many different values, but slight misalignment remains.

2024-08-28 10:50 UTC, tijlleenders approved these changes

2024-08-28 10:51 UTC, tijlleenders commented
Close enough then, @Tushar-4781 agree on code?

2024-08-31 05:14 UTC, Tushar-4781 requested changes

2024-08-31 05:14 UTC, Tushar-4781 commented on src/hooks/useGoalSelection.ts
> +      activeGoalId: goal.id,
we don't use this anymore the active goal id will be fetched from params

2024-08-31 05:14 UTC, Tushar-4781 commented on src/hooks/useGoalSelection.ts
> +      foucusedGoalIndex: focusedIndex,
use a query parameter for this focusing

2024-08-31 05:14 UTC, Tushar-4781 commented on src/hooks/useGoalSelection.ts
> +  useEffect(() => {
please club the code of all the useEffect(s) in a single useEffect. use if else to check which piece to execute

2024-08-31 05:14 UTC, Tushar-4781 commented on src/hooks/useGoalSelection.ts
> +      setFocusedIndex(location.state.foucusedGoalIndex === undefined ? -1 : location.state.foucusedGoalIndex);
create a function wrapped in useCallback that takes the index and handles the focusedIndex state and scrollIntoView functionality for you

2024-09-12 07:20 UTC, Tushar-4781 approved these changes

2024-09-12 07:20 UTC, merged