show goal update confirmation
tijlleenders/ZinZen pull request #2026
Opened 2024-08-20 14:45 UTC by vinaybadgujar102

resolves #1916

2024-08-22 05:23 UTC, tijlleenders requested changes
This was probably implemented three times now, once in main, once by Nicholas, and then again here...  

Anyway, it looks good.  
Please check why the hints toggle is not being persisted. It is probably an unrelated issue. If so, please file a bug for `develop` and this can be merged.

2024-08-23 16:43 UTC, vinaybadgujar102 commented
The hint toggle thing is unrelated, Created a new issue for it.

2024-08-23 16:58 UTC, tijlleenders approved these changes
Great!

2024-08-24 06:32 UTC, Tushar-4781 reviewed
@vinaybadgujar102 Can you explain a bit what exactly happening in code ?

2024-08-24 06:53 UTC, vinaybadgujar102 commented
@Tushar-4781, When the updateGoal function is called to modify a goal, we first generate hashes for both the original goal and the updated goal object passed to the function. We then compare these hashes to detect any differences. If differences are detected, we update the goal in the database and display a confirmation toast; otherwise, we simply return.

2024-08-24 07:00 UTC, Tushar-4781 requested changes

2024-08-24 07:00 UTC, Tushar-4781 commented on src/hooks/useGoalActions.tsx
> +      if (originalGoal) {
club them up -> ( originalGoal && hashObject(originalGoal) !== hashObject(goal))

2024-08-24 08:10 UTC, Tushar-4781 requested changes

2024-08-24 08:10 UTC, Tushar-4781 commented on src/hooks/useGoalActions.tsx
> +      const originalGoal = activeGoal;
no need to duplicate this goal.

2024-08-24 08:10 UTC, Tushar-4781 commented on src/hooks/useGoalActions.tsx
> +      if (originalGoal && hashObject(originalGoal) !== hashObject(goal)) {
use activeGoal directly just add a comment that we are comparing the old and updated version.

2024-08-25 09:20 UTC, Tushar-4781 commented on src/hooks/useGoalActions.tsx
> +    if (isGoalChanged) {
i think you can just move this entire logic in the above block right ?

2024-08-25 15:00 UTC, Tushar-4781 approved these changes

2024-08-25 15:00 UTC, merged