show toast when running scheduler first time
tijlleenders/ZinZen pull request #2028
Opened 2024-08-21 17:34 UTC by vinaybadgujar102

resolves #1816

2024-08-27 15:51 UTC, tijlleenders requested changes
Upon review, the Toast approach is not the right one. It will show the Toast while the goals have already loaded.  

A better way is to have a default DOM element that shows 'Automatic scheduling of your goals in progress...' - and then replace that with the schedule once it's available.  

So instead of showing the empty list of days, only show the message in the middle of the screen.

2024-08-28 10:20 UTC, tijlleenders requested changes
Yup, this is nicer.

Can you remove the italics (makes it harder to read)?
Also, please shorten the sentence to "Auto-scheduling...".

Then we're good to go!

2024-08-29 05:20 UTC, tijlleenders approved these changes
Perfect!

2024-08-31 05:08 UTC, Tushar-4781 requested changes

2024-08-31 05:08 UTC, Tushar-4781 commented on src/pages/MyTimePage/MyTimePage.scss
> +.scheduling-message {
please use a custom class from short.scss for the font weight and font size prop

2024-09-09 03:36 UTC, tijlleenders commented
@Tushar-4781 *bump*

2024-09-09 18:12 UTC, Tushar-4781 approved these changes

2024-09-09 18:12 UTC, merged