fix bugs related to deleted and archived goal items
tijlleenders/ZinZen pull request #2033
Opened 2024-08-27 08:22 UTC by vinaybadgujar102

resolves #1991

2024-08-27 15:46 UTC, tijlleenders approved these changes
Yes this is nice.  
If you can, add the new goal 'pling' sound when restoring the goal.

2024-08-28 11:31 UTC, vinaybadgujar102 commented
> Yes this is nice. If you can, add the new goal 'pling' sound when restoring the goal.

done

2024-08-28 15:01 UTC, tijlleenders requested changes
Great.

I just found a bug:
[Screencast from 2024-08-28 16-57-58.webm](https://github.com/user-attachments/assets/622712fc-e764-4d1b-9c1b-5740479132b8)

The first time around is fine, but the second time around I press the completed Goal circles (no visible immediate effect). That apparently messes things up.

I now realize pressing the goal circle when it's completed (but not yet moved to Done) should have the same effect as if it's already in Done. This could be another issue, up to you.

2024-08-31 05:06 UTC, Tushar-4781 commented on src/components/GoalsComponents/MyGoal/MyGoal.tsx
can you please test collaboration? because if you receive two changes and then at the time of accepting the first change we move on to the second after second the notification dot should disappear. this behavior might get infected with the memo hook.

2024-08-31 06:49 UTC, vinaybadgujar102 commented on src/components/GoalsComponents/MyGoal/MyGoal.tsx
I tested the collaboration and found that the dot doesnt disappear after accepting the change even if MyGoal is not memoized. also there is a bug where collaborated goal appear both as normal and deleted goal. So if I try to open goal options of that collaborated goal I get modal of both deleted and normal goal action options. Thus it is bit hard to compare changes with the develop branch.

2024-09-01 05:06 UTC, Tushar-4781 commented on src/components/GoalsComponents/MyGoal/MyGoal.tsx
Noted

2024-09-01 05:38 UTC, Tushar-4781 commented
@tijlleenders Please check the delete functionality again :) 
@vinaybadgujar102 can you please try collab again now. I've updated the PR

2024-09-01 05:38 UTC, Tushar-4781 commented
Previously deleting a goal was taking too long because of the sound.

2024-09-01 05:50 UTC, tijlleenders requested changes
When I complete multiple goals in Daily routines then select the circle on one of them, nothing happens.

2024-09-01 07:09 UTC, Tushar-4781 commented
@tijlleenders what are you expecting in that case ?

2024-09-01 08:39 UTC, tijlleenders commented
@Tushar-4781 The same behavior as when it would be in 'done'. This is currently working for root goals - but not for subGoals.

2024-09-01 08:43 UTC, tijlleenders commented
The use case is if you mark something as done - then change your mind. You don't want to have to navigate away first.

2024-09-01 10:11 UTC, vinaybadgujar102 commented
@Tushar-4781 the dot is correctly disappearing now after accepting changes according to your comment. Additionally I encountered some bugs related to share functionality for which I will create issues once I confirm them.

> When I complete multiple goals in Daily routines then select the circle on one of them, nothing happens.

@tijlleenders, I fixed this in latest commit.

2024-09-01 10:29 UTC, Tushar-4781 commented
@vinaybadgujar102 I think there's a more efficient way to handle this. Since the component already has access to the length of the goals, it might be better to use that directly rather than passing it in as props

2024-09-01 10:34 UTC, tijlleenders requested changes
Wow we should probably get some tests for all this behavior. Every round of manual testing we find something new. This is going to be hard to catch regressions on without tests.

I noticed now that crossing out a done item and then deleting an item will move the done item to done while moving the deleted to trash.  

I would expect only the deleted item moving to trash, and the done being crossed out untill you navigate away and back again.

2024-09-01 10:48 UTC, vinaybadgujar102 commented
@tijlleenders, I agree. Creating tests for core features will help minimize redundant efforts in fixing regressions introduced by new changes.

2024-09-02 09:03 UTC, Tushar-4781 commented
@tijlleenders can we have test in seperate pr

2024-09-02 09:48 UTC, tijlleenders commented
> @tijlleenders can we have test in seperate pr

Yes, of course.

2024-09-02 10:30 UTC, tijlleenders commented
> I noticed now that crossing out a done item and then deleting an item will move the done item to done while moving the deleted to trash.
> 
> I would expect only the deleted item moving to trash, and the done being crossed out untill you navigate away and back again.

[Screencast from 2024-09-02 12-29-00.webm](https://github.com/user-attachments/assets/2aab448d-688c-4820-aea4-f8290ffd99c4)

2024-09-03 09:38 UTC, Tushar-4781 commented
@vinaybadgujar102 are u fixing it or do you want me to fix it ?

2024-09-03 09:44 UTC, vinaybadgujar102 commented
> @vinaybadgujar102 are u fixing it or do you want me to fix it ?


You can fix it

2024-09-03 15:05 UTC, Tushar-4781 approved these changes

2024-09-03 16:48 UTC, tijlleenders commented
Holding off on 'fixing' this as state update exceptions on default React get complicated.

2024-09-03 16:48 UTC, merged