fix: hints option not updating correctly and hints section not visible in subggoal list
tijlleenders/ZinZen pull request #2044
Opened 2024-09-16 08:51 UTC by vinaybadgujar102

resolves #2043 
resolves #2029

2024-09-16 10:40 UTC, tijlleenders submitted a review, later dismissed

2024-09-27 04:42 UTC, Tushar-4781 requested changes
can you resolve eslint warnings

2024-09-27 04:42 UTC, Tushar-4781 commented on src/api/GoalsAPI/index.ts
>  export const addHintGoaltoMyGoals = async (goal: GoalItem) => {
what if we use Promise.all here ?

2024-10-12 04:25 UTC, vinaybadgujar102 commented
@Tushar-4781 bump

2024-10-12 04:28 UTC, Tushar-4781 approved these changes

2024-10-12 04:28 UTC, merged