fit:removed % Done bar
tijlleenders/ZinZen pull request #2047
Opened 2024-09-18 06:31 UTC by codervinod123

Resolves #2046

2024-09-18 06:37 UTC, tijlleenders commented
@codervinod123 Is this ready for review?  
The grey bar can also be removed, not only the %done text.

2024-09-18 07:05 UTC, codervinod123 commented
> @codervinod123 Is this ready for review? The grey bar can also be removed, not only the %done text.
@tijlleenders let me remove

2024-09-18 07:59 UTC, codervinod123 commented
@tijlleenders please review

2024-09-18 08:43 UTC, tijlleenders approved these changes
@codervinod123 From UI side this looks great.  

Has all dead code been removed too? So like a CSS classes/variables/components/etc that were only used by the 'Done' component, and are now 'dead code'?  

There's a lot of code formatting changes too. Maybe @vinaybadgujar102 can advise what the standard formatter is for our project and how to implement this. Otherwise it makes it hard to review the code, as formatting changes are mixed in with 'real' changes to the code...

2024-09-19 01:35 UTC, codervinod123 commented
@tijlleenders 

All dead code been removed.
There's a lot of code formatting changes just because of linting and prettier rule for this code base

2024-09-19 03:03 UTC, vinaybadgujar102 requested changes

2024-09-19 03:03 UTC, vinaybadgujar102 commented on src/components/MyTimeComponents/ColorBands.tsx
>  const ColorBands: React.FC<IColorBands> = ({ list, tasksStatus, day, active }) => {
remove unnecessary props

2024-09-19 04:54 UTC, codervinod123 commented on src/components/MyTimeComponents/ColorBands.tsx
>    });
got it , Thanks

2024-09-20 04:34 UTC, vinaybadgujar102 commented on src/components/MyTimeComponents/ColorBands.tsx
>    });
hey @codervinod123. I noticed that correct lines are not highlighted by me in this comment. Sorry for the inconvenience. 
You can remove the code from line 17 to 37 which includes all business logic. Then remove the unused props.

2024-09-24 05:09 UTC, codervinod123 commented
@vinay can you review  https://github.com/tijlleenders/ZinZen/pull/2047/commits/f5a8f5cc839bd17aecbfc711b323f519d9e575fd

2024-09-24 12:38 UTC, vinaybadgujar102 approved these changes

2024-09-24 12:39 UTC, vinaybadgujar102 commented
@codervinod123 Thanks for the contribution!

2024-09-24 12:40 UTC, merged