feat: remove confirmation and show toast on goal delete
tijlleenders/ZinZen pull request #2058
Opened 2024-10-12 15:51 UTC by harshalranjhani

Removed the confirmation modal when user tries to delete a goal. Instead it shows a toast directly which says "Moved to trash! We'll delete it in 7 days."

Fixes #2054 

Screenshot:
![image](https://github.com/user-attachments/assets/1d9cf3f3-807c-4662-94a8-7eb6c960af74)

2024-10-12 17:03 UTC, tijlleenders submitted a review, later dismissed
Thanks!

2024-10-13 06:33 UTC, vinaybadgujar102 requested changes

2024-10-13 06:33 UTC, vinaybadgujar102 commented on src/components/GoalsComponents/MyGoalActions/RegularGoalActions.tsx
> +import { lastAction, openDevMode, displayConfirmation, displayToast, displayToast } from "@src/store";
remove duplicate import of displayToast

2024-10-13 06:36 UTC, harshalranjhani commented on src/components/GoalsComponents/MyGoalActions/RegularGoalActions.tsx
> +import { lastAction, openDevMode, displayConfirmation, displayToast, displayToast } from "@src/store";
fixed.

2024-10-13 06:40 UTC, vinaybadgujar102 approved these changes

2024-10-13 06:40 UTC, vinaybadgujar102 commented
@harshalranjhani Thanks for contributing! We appreciate your work and feel free to contribute more!

2024-10-13 06:41 UTC, merged