Add escape key event listener to call onCancel function on modals
tijlleenders/ZinZen pull request #2059
Opened 2024-10-13 09:18 UTC by aarifkhan7

resolves #2052

2024-10-13 12:46 UTC, vinaybadgujar102 requested changes

2024-10-14 08:31 UTC, vinaybadgujar102 approved these changes

2024-10-14 08:35 UTC, vinaybadgujar102 commented
Great work! @aarifkhan7 🎉. We'd love more contributions from you

2024-10-14 08:35 UTC, merged

2024-10-15 07:50 UTC, aarifkhan7 commented
Thank you @vinaybadgujar102 :)