fix: show scrollbar on overflow
tijlleenders/ZinZen pull request #2061
Opened 2024-10-13 12:36 UTC by rupali-codes

Added scrollbar on goals section. User can now scroll through the content. Also, I've added z-index to properly show the footer on overflow.

Closes #2057 

![image](https://github.com/user-attachments/assets/549b5209-99a8-4155-8fde-9dfa6818e922)

2024-10-13 12:43 UTC, tijlleenders approved these changes
Awesome @rupali-codes !

2024-10-13 12:44 UTC, tijlleenders commented
@Tushar-4781 Is the code OK?

2024-10-15 03:40 UTC, Tushar-4781 requested changes

2024-10-15 03:40 UTC, Tushar-4781 commented on src/global.scss
> +.mainDiv {
You can move this CSS back into the JSX file. Another reason for doing this is that the app layout is accessed less frequently compared to the global.scss, which mainly contains classes that are used across multiple elements all over the app.

2024-10-15 03:40 UTC, Tushar-4781 commented on src/global.scss
> +.mainDiv::-webkit-scrollbar {
add a comment on top this /* App Layout */

2024-10-15 03:40 UTC, Tushar-4781 commented on src/layouts/AppLayout.tsx
> +    <div className="mainDiv">{children}</div>
you can rename the class -> appLayout

2024-10-15 09:56 UTC, rupali-codes commented
@Tushar-4781 i have made the requested changes.

2024-10-16 03:24 UTC, Tushar-4781 approved these changes

2024-10-16 03:25 UTC, merged