restrict archived suggestions to parent goals only and fix subgoal render problem
tijlleenders/ZinZen pull request #2062
Opened 2024-10-14 09:57 UTC by vinaybadgujar102

Fixed:

- only show suggestion of archived child goals of a parent
- fix re-render problem
- show different toast msg when suggested goal is added.

2024-10-14 15:45 UTC, tijlleenders approved these changes
Great, PR does what it says it does!

2024-10-15 03:53 UTC, Tushar-4781 requested changes

2024-10-15 03:53 UTC, Tushar-4781 commented on src/api/GoalsAPI/index.ts
> +  if (goalId.trim() === "") {
try this => if( !goalId.trim() )

2024-10-15 03:53 UTC, Tushar-4781 commented on src/api/GoalsAPI/index.ts
> +export const fetchArchivedGoalByTitle = async (goalId: string, parentGoalId: string) => {
if we say byTitle then arg should be named as title. can we change that goalId to goalTitle or title?

2024-10-15 03:53 UTC, Tushar-4781 commented on src/api/GoalsAPI/index.ts
> +  const lowerCaseValue = goalId.toLowerCase();
maybe we can rename it something like searchTitle ?

2024-10-15 03:53 UTC, Tushar-4781 commented on src/api/GoalsAPI/index.ts
> +    const allChildren = await Promise.all(
maybe name it to -> allDescendantGoals

2024-10-15 03:53 UTC, Tushar-4781 commented on src/api/GoalsAPI/index.ts
> +  const allChildren = await getAllChildrenGoals(parentGoalId);
allDescendantGoals

2024-10-15 03:53 UTC, Tushar-4781 commented on src/contexts/parentGoal-context.tsx
> +    if (suggestedGoal === null) {
if (!suggestedGoal) {

2024-10-15 03:53 UTC, Tushar-4781 commented on src/hooks/useGoalActions.tsx
> +          message: "Goal (re)created!",
u can just use ternary operator for the message field

2024-10-15 03:53 UTC, Tushar-4781 commented on src/hooks/useGoalStore.tsx
> +    const newState = {
no need of variable u can place directly in there

2024-10-16 09:40 UTC, Tushar-4781 approved these changes

2024-10-16 09:40 UTC, merged