show scheduled status in edit modal
tijlleenders/ZinZen pull request #2077
Opened 2024-11-10 08:12 UTC by vinaybadgujar102

resolves #2006

2024-11-10 08:15 UTC, tijlleenders submitted a review, later dismissed
Excellent!

2024-11-10 08:16 UTC, tijlleenders commented
@Tushar-4781 OK with the code?

2024-11-16 12:19 UTC, Tushar-4781 requested changes

2024-11-16 12:19 UTC, Tushar-4781 commented on src/components/GoalsComponents/GoalConfigModal/ConfigGoal.scss
> +  font-size: 14px;
use font class from short.scss

2024-11-29 10:40 UTC, vinaybadgujar102 commented
@Tushar-4781 bump

2024-12-06 05:21 UTC, Tushar-4781 approved these changes

2024-12-06 05:21 UTC, merged