allow deleting contacts (WIP)
tijlleenders/ZinZen pull request #2086
Opened 2024-11-30 13:16 UTC by vinaybadgujar102

2024-11-30 13:18 UTC, vinaybadgujar102 commented
@tijlleenders what should happen on receiver side when a contact is deleted by a user?

2024-11-30 13:28 UTC, tijlleenders commented
> @tijlleenders what should happen on receiver side when a contact is deleted by a user?

Interesting question... I see three possible reasons for deleting a contact(device):
- that contact(device) no longer exists
- the relationship is broken bilaterally (both parties don't want to share)
- the relationship is broken unilaterally (only one party doesn't want to share)
Only in the last case there is a reason to:
- maintain the relationship id
- possibly inform the other party they are being 'ghosted'

For now, let's not add any extra requirements.  
Deleting is one-sided and doesn't affect the other party or the relationship id.

2025-02-01 06:31 UTC, tijlleenders commented
I think we can remove the 'blocked' label?

2025-02-22 09:38 UTC, tijlleenders requested changes
This is pretty cool, nice work!  

There is a small glitch in the way shared subgoals are being handled:  
[
[Screencast From 2025-02-22 10-37-29.webm](https://github.com/user-attachments/assets/a05f6560-d8c0-410f-b963-5bb5f2cd02f9)
](url)

2025-02-23 08:54 UTC, vinaybadgujar102 commented
> This is pretty cool, nice work!
> 
> There is a small glitch in the way shared subgoals are being handled: [ [Screencast From 2025-02-22 10-37-29.webm](https://github.com/user-attachments/assets/a05f6560-d8c0-410f-b963-5bb5f2cd02f9) ](url)

@tijlleenders, I cant reproduce it. Could you please provide details on how you arrived at this state of goals in partner mode?

2025-02-23 11:04 UTC, tijlleenders commented
@vinaybadgujar102 Maybe it's the commit you did, but I can't get a sharing link anymore.

2025-02-23 11:04 UTC, tijlleenders requested changes
Sharing link not working so can't test or try to reproduce the issue.

2025-02-25 11:45 UTC, tijlleenders commented
@vinaybadgujar102 Can you check what's failing the Playwright test?  
I'd like to keep dev green.

2025-02-27 11:48 UTC, vinaybadgujar102 commented
@tijlleenders, fixed the test and please check again if this feature is correctly

2025-02-28 13:06 UTC, tijlleenders approved these changes
Nice!

Also like the toast for when there are no contacts remaining + redirect.

2025-02-28 13:06 UTC, tijlleenders commented
@Tushar-4781 Can you do tech review on this?

2025-03-07 14:01 UTC, merged