Tijlleenders main
tijlleenders/ZinZen pull request #253
Opened 2022-04-30 14:07 UTC by GithinjiHans

2022-04-30 14:40 UTC, tijlleenders commented
Should the package-lock.json be deleted? 
[This article from a relatively authoratative source says no](https://dev.to/adamklein/package-lock-json-in-git-or-not-50l5).

2022-04-30 15:25 UTC, Tushar-4781 commented
The article is correct, it shouldn't be deleted. Also, Cypress will fail to run the test.

2022-04-30 15:28 UTC, Tushar-4781 commented
@GithinjiHans, please make sure to give informative names to the pull requests. The branch name is not the convention to follow for PR naming.

2022-04-30 15:36 UTC, Tushar-4781 approved these changes

2022-04-30 15:36 UTC, Tushar-4781 commented on src/components/todoList/TodoListForm.jsx
> +
Don't add more than one line gap between the code.

2022-04-30 15:36 UTC, Tushar-4781 commented on src/translations/hi/translation.json
> +    "myGoalsMessage":"",
Maybe use a translation service like google translate.

2022-04-30 15:39 UTC, Tushar-4781 requested changes
Bring back the package-lock.json.

2022-05-04 17:11 UTC, GithinjiHans commented on src/translations/hi/translation.json
> +    "myGoalsMessage":"",
Done

2022-05-04 18:51 UTC, closed without merging