Make the duration parser test pass
tijlleenders/ZinZen pull request #362
Opened 2022-05-22 19:38 UTC by GithinjiHans

2022-05-23 16:48 UTC, tijlleenders commented
@GithinjiHans 
Should we delete this PR?
If it is not finished please convert it to draft.

2022-05-23 18:09 UTC, GithinjiHans commented
I've solved the merge conflicts

2022-05-23 19:14 UTC, tijlleenders requested changes
Please use descriptive names.
'''
expect(timeSuggestion()).toEqual(a);
```
What is a?

2022-05-24 04:08 UTC, tijlleenders approved these changes

2022-05-24 04:09 UTC, merged