Feature/faq page
tijlleenders/ZinZen pull request #391
Opened 2022-06-03 17:59 UTC by mallikarai05

Make the FAQ Page for first time use #373

2022-06-04 05:00 UTC, tijlleenders commented
From a UI perspective this is exactly what was required.

2022-06-04 13:29 UTC, pulkitvyas08 requested changes
Delete the header component `HeaderQueryPage`. This is redundant code.  You can find the header in `HeaderDashboard`, use that one.

2022-06-05 17:13 UTC, pulkitvyas08 approved these changes

2022-06-05 17:48 UTC, merged

2022-06-05 18:46 UTC, tijlleenders commented
Closes #373