Made my time page the default entry page
tijlleenders/ZinZen pull request #529
Opened 2022-07-09 04:02 UTC by GithinjiHans

2022-07-09 11:27 UTC, Tushar-4781 reviewed
since the dashboard is no longer the default entry page. starting test of all other pages has to be modified.

2022-07-09 15:22 UTC, tijlleenders requested changes
@GithinjiHans 

The first time I open the app it works as expected. I go through the setup choices (language and theme) and intro, thrn I land on MyTime.

However as a returning user, the app still opens on the Dashboard.

Can you fix that?

2022-07-09 17:37 UTC, GithinjiHans commented
> @GithinjiHans
> 
> The first time I open the app it works as expected. I go through the setup choices (language and theme) and intro, thrn I land on MyTime.
> 
> However as a returning user, the app still opens on the Dashboard.
> 
> Can you fix that?
Sure

2022-07-10 06:35 UTC, tijlleenders approved these changes

2022-07-10 06:35 UTC, merged