bug for light and dark color text translations resolved
tijlleenders/ZinZen pull request #919
Opened 2023-01-09 18:55 UTC by shoonyank

Hi Tushar, the bug that revolved around "Light colors" and "Dark colors" text translation on Theme Choice page has been resolved.
To resolve it, I first read the complete details about the bug. Then, as mentioned that the text was hard coded, so I concluded that this was not a bug but just that maybe the translator function wasn't yet implemented on the page.
I looked on the pages where the translation was working fine, so I just read more about it on the i18 documentation page. And accordingly translated both the strings in the necessary languages and copied those translations over the translation pages that are already present. 
After this, I just called the translator function with these strings as parameters in them. This worked well and it was translating it for all languages perfectly.
Please have a look and do the needful.

2023-01-10 10:24 UTC, Tushar-4781 requested changes
Please add issue number. Which issue does this PR resolves

2023-01-10 19:44 UTC, tijlleenders commented
> Please add issue number. Which issue does this PR resolves

@shoonyank Check https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword for more info.

2023-01-13 08:10 UTC, Tushar-4781 commented
Closing this, as there is no activity on requested changes from 3 days

2023-01-15 07:45 UTC, tijlleenders commented
@Tushar-4781 Closing this PR does not fix the issue #894 
Closes #894 

I think this is good to merge now that the issue is mentioned.

2023-01-16 16:35 UTC, merged