move theme switcher to sidebar and replace with +
tijlleenders/ZinZen pull request #939
Opened 2023-01-16 15:49 UTC by elyessAR

Closes #927.
Moved theme switcher to sidebar and replaced with +, user will be redirected to myGoals page and "add new goal" will open up" when + pressed from My time page.

2023-01-16 16:33 UTC, Tushar-4781 reviewed
Try something better, the toggler is not in center and in some devices it is shifting to right

2023-01-16 16:33 UTC, Tushar-4781 commented on src/components/HeaderDashboard/HeaderDashboard.scss
> +  margin-left: 138px;
Not a good way to position an element to center.

2023-01-16 16:50 UTC, elyessAR commented
is this better @Tushar-4781 
![Screenshot_4](https://user-images.githubusercontent.com/49849558/212729804-fc2f43e6-feb6-4458-9839-fcd07147f3ef.png)
![Screenshot_5](https://user-images.githubusercontent.com/49849558/212729842-ae7fac10-7d25-448e-9cd4-4518c76b26ba.png)

2023-01-16 16:53 UTC, Tushar-4781 commented
> is this better ?@Tushar-4781 ![Screenshot_4](https://user-images.githubusercontent.com/49849558/212729804-fc2f43e6-feb6-4458-9839-fcd07147f3ef.png) ![Screenshot_5](https://user-images.githubusercontent.com/49849558/212729842-ae7fac10-7d25-448e-9cd4-4518c76b26ba.png)

without commit i can't say anything. but yes the ss u sent is correct

2023-01-16 17:00 UTC, elyessAR commented
> > is this better ?@Tushar-4781 ![Screenshot_4](https://user-images.githubusercontent.com/49849558/212729804-fc2f43e6-feb6-4458-9839-fcd07147f3ef.png) ![Screenshot_5](https://user-images.githubusercontent.com/49849558/212729842-ae7fac10-7d25-448e-9cd4-4518c76b26ba.png)
> 
> without commit i can't say anything. but yes the ss u sent is correct

Ok, glad you liked it I'll commit

2023-01-17 09:28 UTC, Tushar-4781 requested changes
![image](https://user-images.githubusercontent.com/39093015/212860457-9639cb2c-0c36-484a-b0c1-eb7788f3469d.png)

Can you add some margin between options div and toggler

2023-01-17 15:04 UTC, elyessAR commented
> ![image](https://user-images.githubusercontent.com/39093015/212860457-9639cb2c-0c36-484a-b0c1-eb7788f3469d.png)
> 
> Can you add some margin between options div and toggler

Sure

2023-01-17 16:34 UTC, Tushar-4781 approved these changes

2023-01-17 16:34 UTC, merged